# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: anandchowdary2005@gmail.com
author_name: anand
preset_name: starter
project_name: Veritas-frontend

